FROM node:alpine AS builder
ENV NODE_ENV production
WORKDIR /app
COPY /app/financas/package.json .
COPY /app/financas/yarn.lock .
RUN npm install --production
COPY /app/financas .
RUN npm run build

FROM nginx:stable-alpine3.17 as producao
ENV NODE_ENV production
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]